version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "network.host: 0.0.0.0"
      - "network.publish_host: 0.0.0.0"
      - "discovery.zen.minimum_master_nodes: 1"
      - cluster.initial_master_nodes=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data:rw
    working_dir: /usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    links:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
          - "ELASTICSEARCH_URL=http://localhost:9200"